export const masks = {
    Afghanistan: "+93-###-###-##",
    Australia: "+61-#-####-####",
    Azerbaijan: "+994-##-###-##-##",
    Belgium: "+32(###)###-###",
    BosniaAndHerzegovina: "387-##-#####",
    China: "+86(###)####-###",
    Denmark: "+45-##-##-##-##",
    Ecuador: "+593-##-###-####",
    Egypt: "+20(###)###-####",
    UnitedStates: "+1(###)###-####",
    UnitedKingdom: "+44-##-####-####",
    Russia: "+7(9##)###-##-##",
    Romania: "+40-##-###-####",
    Turkey: "+90(###)###-####",
    SouthKorea: "82-##-###-####",
    Kazakhstan: "+7(###)###-##-##",
    Kyrgyzstan: "+996(###)###-###",
    NewZeeland: "+64-##-###-###",
    France: "+33(###)###-###",
    Spain: "+34(###)###-###",
    Bulgaria: "+359(###)###-###",
    Italy: "+39(###)####-###",
    Japan: "+81-##-####-####",
}